/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package defence.system;

import static defence.system.Strength.CLOSED;
import static defence.system.Strength.HIGH;
import static defence.system.Strength.LOW;
import static defence.system.Strength.MEDIUM;
import static defence.system.Strength.STRONG;

/**
 *
 * @author danid
 */
public class Helicopter extends javax.swing.JFrame implements Observer {
    private ObservableInterface Observable;
    private Strength strength;
    private int position;
    
    /** Creates new form Helicopter */
    public Helicopter() {
        initComponents();
        setVisible(true);
    }
    Helicopter(ObservableInterface Observable){
	this.Observable=Observable;
        initComponents();
        setVisible(true);
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        //btn4.setEnabled(false);
    }
    @Override
    public void update(boolean areaClear,String commanMsg){
        areaClearText.setText(areaClear==true ? "Area Clear":"Area Not Clear");
	helicopterMsg.setText(commanMsg);
        
    }
    @Override
    public void update(String[] subInfoArray){
        
    }
    @Override
    public void update(String[] heliInfoArray,int a) {
        
    }
    @Override
    public void update(String[] tankInfoArray,int a,int b){
        
    }
    @Override
    public void update(String subMassage){
        
    }
    @Override
    public void update(String heliMassage,double a){
        
    }
    @Override
    public void update(String tankMassage,double a,double b){
        
    }
    @Override
    public void update(int position){
        this.position = position;
        if(position<=20&&position>=0){
           strength = Strength.LOW; 
        }else if(position<=40&&position>20){
            strength = Strength.MEDIUM; 
        }else if(position<=60&&position>40){
            strength = Strength.HIGH; 
        }else if(position<=80&&position>60){
            strength = Strength.STRONG; 
        }else{
            strength = Strength.CLOSED; 
        }
        
        if(positionCheck.isSelected()){
           switch (strength) {
                case LOW:
                    btn1.setEnabled(false);
                    btn2.setEnabled(false);
                    btn3.setEnabled(false);
                    //btn4.setEnabled(false);
                    break;
                case MEDIUM:
                    btn1.setEnabled(true);
                    btn2.setEnabled(false);
                    btn3.setEnabled(false);
                    //btn4.setEnabled(false);
                    break;
                case HIGH:
                    btn1.setEnabled(true);
                    btn2.setEnabled(true);
                    btn3.setEnabled(false);
                    //btn4.setEnabled(false);
                    break;
                case STRONG:
                    btn1.setEnabled(true);
                    btn2.setEnabled(true);
                    btn3.setEnabled(true);
                    //btn4.setEnabled(false);
                    break;
                case CLOSED:
                    btn1.setEnabled(true);
                    btn2.setEnabled(true);
                    btn3.setEnabled(true);
                    //btn4.setEnabled(true);
                    break;
                default:
                    break;
                } 
        }else{
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            //btn4.setEnabled(false);
        }
    }
    @Override
    public void update(String subText,int a,double b){
    
    }
    @Override
    public void update(String tankText,int a,int c,double b){
        
    }
    
    @Override
    public void update(String heliText,int a,int c,int d,double b){
        helicopterMsg.setText(heliText);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        heliFuelCount = new javax.swing.JSlider();
        heliMassage = new javax.swing.JTextField();
        heliMassageBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        heliSoldierCount = new javax.swing.JSpinner();
        heliAmmoCount = new javax.swing.JSpinner();
        positionCheck = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        helicopterMsg = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        areaClearText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defence/system/images/Green radar.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 91, 218, -1));

        btn1.setBackground(new java.awt.Color(204, 0, 0));
        btn1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btn1.setText("Shoot");
        btn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 91, 237, 32));

        btn2.setBackground(new java.awt.Color(204, 0, 0));
        btn2.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btn2.setText("Missile Operation");
        btn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 129, 237, 39));

        btn3.setBackground(new java.awt.Color(204, 0, 0));
        btn3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btn3.setText("Laser Operation");
        btn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 177, 237, 38));

        heliFuelCount.setBackground(new java.awt.Color(0, 0, 0));
        heliFuelCount.setForeground(new java.awt.Color(153, 153, 153));
        heliFuelCount.setMajorTickSpacing(20);
        heliFuelCount.setMinorTickSpacing(10);
        heliFuelCount.setOrientation(javax.swing.JSlider.VERTICAL);
        heliFuelCount.setPaintLabels(true);
        heliFuelCount.setPaintTicks(true);
        heliFuelCount.setSnapToTicks(true);
        heliFuelCount.setValue(0);
        heliFuelCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heliFuelCountStateChanged(evt);
            }
        });
        getContentPane().add(heliFuelCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 117, 134, 423));

        heliMassage.setBackground(new java.awt.Color(0, 0, 0));
        heliMassage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        heliMassage.setForeground(new java.awt.Color(0, 153, 0));
        heliMassage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        getContentPane().add(heliMassage, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 552, 473, 37));

        heliMassageBtn.setBackground(new java.awt.Color(0, 153, 0));
        heliMassageBtn.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        heliMassageBtn.setText("Send");
        heliMassageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        heliMassageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliMassageBtnActionPerformed(evt);
            }
        });
        getContentPane().add(heliMassageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 554, 147, 37));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Soldier Count");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 448, -1, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Ammo Count");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 506, 99, -1));

        heliSoldierCount.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        heliSoldierCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heliSoldierCountStateChanged(evt);
            }
        });
        getContentPane().add(heliSoldierCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 445, 70, -1));

        heliAmmoCount.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        heliAmmoCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heliAmmoCountStateChanged(evt);
            }
        });
        getContentPane().add(heliAmmoCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 503, 70, -1));

        positionCheck.setBackground(new java.awt.Color(0, 0, 0));
        positionCheck.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        positionCheck.setForeground(new java.awt.Color(204, 204, 204));
        positionCheck.setText("Position");
        positionCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionCheckActionPerformed(evt);
            }
        });
        getContentPane().add(positionCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 221, 90, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Fuel");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 92, 37, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defence/system/images/logo.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 75, -1));

        jLabel7.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Helicopter Defence System");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 6, 540, 79));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(0, 153, 0));

        helicopterMsg.setBackground(new java.awt.Color(0, 0, 0));
        helicopterMsg.setColumns(20);
        helicopterMsg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helicopterMsg.setForeground(new java.awt.Color(0, 153, 0));
        helicopterMsg.setRows(5);
        jScrollPane1.setViewportView(helicopterMsg);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("main console");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 246, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        areaClearText.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        areaClearText.setForeground(new java.awt.Color(0, 153, 0));
        areaClearText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areaClearText.setText("Area Not Clear");
        areaClearText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(areaClearText, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaClearText, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 440, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defence/system/images/Background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void heliMassageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliMassageBtnActionPerformed
        String Massage = "HELICOPTER : "+heliMassage.getText();
        Observable.setheliMassage(Massage);// TODO add your handling code here:
    }//GEN-LAST:event_heliMassageBtnActionPerformed

    private void positionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionCheckActionPerformed
        boolean isSelected = positionCheck.isSelected();
            if(isSelected==false){
                btn1.setEnabled(false);
                btn2.setEnabled(false);
                btn3.setEnabled(false);
                //btn4.setEnabled(false);
            }else{
                update(this.position);
            }// TODO add your handling code here:
    }//GEN-LAST:event_positionCheckActionPerformed

    private void heliSoldierCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heliSoldierCountStateChanged
        String[] heliInfoarray = {
            ""+heliSoldierCount.getValue(),
            ""+heliAmmoCount.getValue(),
            ""+heliFuelCount.getValue()+"%"};
        Observable.setHeliInfo(heliInfoarray);// TODO add your handling code here:
    }//GEN-LAST:event_heliSoldierCountStateChanged

    private void heliAmmoCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heliAmmoCountStateChanged
        String[] heliInfoarray = {
            ""+heliSoldierCount.getValue(),
            ""+heliAmmoCount.getValue(),
            ""+heliFuelCount.getValue()+"%"};
        Observable.setHeliInfo(heliInfoarray);// TODO add your handling code here:
    }//GEN-LAST:event_heliAmmoCountStateChanged

    private void heliFuelCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heliFuelCountStateChanged
        String[] heliInfoarray = {
            ""+heliSoldierCount.getValue(),
            ""+heliAmmoCount.getValue(),
            ""+heliFuelCount.getValue()+"%"};
        Observable.setHeliInfo(heliInfoarray);// TODO add your handling code here:
    }//GEN-LAST:event_heliFuelCountStateChanged

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        int ammo = (int) heliAmmoCount.getValue();
        if(ammo<=0){
           helicopterMsg.setText("WARNING : Ammo count is empty...");
        }else{
            ammo--;
            heliAmmoCount.setValue(ammo);
        }//// TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helicopter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaClearText;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JSpinner heliAmmoCount;
    private javax.swing.JSlider heliFuelCount;
    private javax.swing.JTextField heliMassage;
    private javax.swing.JButton heliMassageBtn;
    private javax.swing.JSpinner heliSoldierCount;
    private javax.swing.JTextArea helicopterMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox positionCheck;
    // End of variables declaration//GEN-END:variables

}
