/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence.system;

import static defence.system.Strength.CLOSED;
import static defence.system.Strength.HIGH;
import static defence.system.Strength.LOW;
import static defence.system.Strength.MEDIUM;
import static defence.system.Strength.STRONG;

/**
 *
 * @author danid
 */
public class Tank extends javax.swing.JFrame implements Observer{
    private ObservableInterface Observable;
    private Strength strength;
    private int position;
    

    /**
     * Creates new form Tank
     */
    public Tank() {
        initComponents();
        setVisible(true);
    }
    Tank(ObservableInterface Observable){
	this.Observable=Observable;
        initComponents();
        setVisible(true);
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
    }
    @Override
    public void update(boolean areaClear,String commanMsg){
	tankMsg.setText(commanMsg);
        areaClearText.setText(areaClear==true ? "Area Clear":"Area Not Clear"); 
    }
    @Override
    public void update(String[] subInfoArray){
        
    }
    @Override
    public void update(String[] heliInfoArray,int a) {
        
    }
    @Override
    public void update(String[] tankInfoArray,int a,int b){
        
    }
    @Override
    public void update(String subMassage){
        
    }
    @Override
    public void update(String heliMassage,double a){
        
    }
    @Override
    public void update(String tankMassage,double a,double b){
        
    }
    @Override
    public void update(int position){
        this.position = position;
        if(position<=20&&position>=0){
           strength = Strength.LOW; 
        }else if(position<=40&&position>20){
            strength = Strength.MEDIUM; 
        }else if(position<=60&&position>40){
            strength = Strength.HIGH; 
        }else if(position<=80&&position>60){
            strength = Strength.STRONG; 
        }else{
            strength = Strength.CLOSED; 
        }
        
        if(positionCheck.isSelected()){
           switch (strength) {
                case LOW:
                    btn1.setEnabled(false);
                    btn2.setEnabled(false);
                    btn3.setEnabled(false);
                    btn4.setEnabled(false);
                    break;
                case MEDIUM:
                    btn1.setEnabled(true);
                    btn2.setEnabled(false);
                    btn3.setEnabled(false);
                    btn4.setEnabled(false);
                    break;
                case HIGH:
                    btn1.setEnabled(true);
                    btn2.setEnabled(true);
                    btn3.setEnabled(false);
                    btn4.setEnabled(false);
                    break;
                case STRONG:
                    btn1.setEnabled(true);
                    btn2.setEnabled(true);
                    btn3.setEnabled(true);
                    btn4.setEnabled(false);
                    break;
                case CLOSED:
                    btn1.setEnabled(true);
                    btn2.setEnabled(true);
                    btn3.setEnabled(true);
                    btn4.setEnabled(true);
                    break;
                default:
                    break;
            } 
        }else{
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
        }
    }
    @Override
    public void update(String subText,int a,double b){
    
    }
    @Override
    public void update(String tankText,int a,int c,double b){
        tankMsg.setText(tankText);
    }
    
    @Override
    public void update(String heliText,int a,int c,int d,double b){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tankFuelCount = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tankSoldierCount = new javax.swing.JSpinner();
        tankAmmoCount = new javax.swing.JSpinner();
        tankMassage = new javax.swing.JTextField();
        tankMassageBtn = new javax.swing.JButton();
        positionCheck = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tankMsg = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        areaClearText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defence/system/images/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 6, 76, -1));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tank Defence System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 6, 630, 76));

        tankFuelCount.setBackground(new java.awt.Color(0, 0, 0));
        tankFuelCount.setForeground(new java.awt.Color(204, 204, 204));
        tankFuelCount.setMajorTickSpacing(20);
        tankFuelCount.setMinorTickSpacing(10);
        tankFuelCount.setOrientation(javax.swing.JSlider.VERTICAL);
        tankFuelCount.setPaintLabels(true);
        tankFuelCount.setPaintTicks(true);
        tankFuelCount.setSnapToTicks(true);
        tankFuelCount.setValue(0);
        tankFuelCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tankFuelCountStateChanged(evt);
            }
        });
        getContentPane().add(tankFuelCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, 512));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defence/system/images/Red radar.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 8, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, 512, 353));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Fuel");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 37, -1));

        btn1.setBackground(new java.awt.Color(204, 0, 0));
        btn1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btn1.setText("Shoot");
        btn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 120, 65));

        btn2.setBackground(new java.awt.Color(204, 0, 0));
        btn2.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btn2.setText("Missile Operation");
        btn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 192, 120, 65));

        btn3.setBackground(new java.awt.Color(204, 0, 0));
        btn3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btn3.setText("Redar Oparation");
        btn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 283, 120, 65));

        btn4.setBackground(new java.awt.Color(204, 0, 0));
        btn4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btn4.setText("Rotate Shooting");
        btn4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 375, 120, 65));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Soldier Count");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 493, 104, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Ammo Count");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 526, 109, -1));

        tankSoldierCount.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        tankSoldierCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tankSoldierCountStateChanged(evt);
            }
        });
        getContentPane().add(tankSoldierCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 490, 118, -1));

        tankAmmoCount.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        tankAmmoCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tankAmmoCountStateChanged(evt);
            }
        });
        getContentPane().add(tankAmmoCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 523, 118, -1));

        tankMassage.setBackground(new java.awt.Color(0, 0, 0));
        tankMassage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tankMassage.setForeground(new java.awt.Color(0, 153, 0));
        tankMassage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        getContentPane().add(tankMassage, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 642, 523, 30));

        tankMassageBtn.setBackground(new java.awt.Color(0, 153, 0));
        tankMassageBtn.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        tankMassageBtn.setText("Send");
        tankMassageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        tankMassageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankMassageBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tankMassageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 160, 30));

        positionCheck.setBackground(new java.awt.Color(0, 0, 0));
        positionCheck.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        positionCheck.setForeground(new java.awt.Color(204, 204, 204));
        positionCheck.setText("Position");
        positionCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionCheckActionPerformed(evt);
            }
        });
        getContentPane().add(positionCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 452, 120, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        tankMsg.setBackground(new java.awt.Color(0, 0, 0));
        tankMsg.setColumns(20);
        tankMsg.setForeground(new java.awt.Color(0, 153, 0));
        tankMsg.setRows(5);
        jScrollPane1.setViewportView(tankMsg);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("main console");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 490, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        areaClearText.setBackground(new java.awt.Color(0, 0, 0));
        areaClearText.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        areaClearText.setForeground(new java.awt.Color(0, 153, 0));
        areaClearText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areaClearText.setText("Area Not Clear");
        areaClearText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaClearText, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaClearText, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 556, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defence/system/images/Background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tankMassageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankMassageBtnActionPerformed
        String Massage = "TANK : "+tankMassage.getText();
        Observable.settankMassage(Massage);    // TODO add your handling code here:
    }//GEN-LAST:event_tankMassageBtnActionPerformed

    private void positionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionCheckActionPerformed
    boolean isSelected = positionCheck.isSelected();
            if(isSelected==false){
                btn1.setEnabled(false);
                btn2.setEnabled(false);
                btn3.setEnabled(false);
                btn4.setEnabled(false);
            }else{
                update(this.position);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_positionCheckActionPerformed

    private void tankSoldierCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tankSoldierCountStateChanged
        String[] tankInfoarray = {
            ""+tankSoldierCount.getValue(),
            ""+tankAmmoCount.getValue(),
            ""+tankFuelCount.getValue()+"%"};
        Observable.setTankInfo(tankInfoarray);// TODO add your handling code here:
    }//GEN-LAST:event_tankSoldierCountStateChanged

    private void tankAmmoCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tankAmmoCountStateChanged
        String[] tankInfoarray = {
            ""+tankSoldierCount.getValue(),
            ""+tankAmmoCount.getValue(),
            ""+tankFuelCount.getValue()+"%"};
        Observable.setTankInfo(tankInfoarray);// TODO add your handling code here:
    }//GEN-LAST:event_tankAmmoCountStateChanged

    private void tankFuelCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tankFuelCountStateChanged
        String[] tankInfoarray = {
            ""+tankSoldierCount.getValue(),
            ""+tankAmmoCount.getValue(),
            ""+tankFuelCount.getValue()+"%"};
        Observable.setTankInfo(tankInfoarray);// TODO add your handling code here:
    }//GEN-LAST:event_tankFuelCountStateChanged

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        int ammo = (int) tankAmmoCount.getValue();
        if(ammo<=0){
           tankMsg.setText("WARNING : Ammo count is empty...");
        }else{
            ammo--;
            tankAmmoCount.setValue(ammo);
        }//        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaClearText;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox positionCheck;
    private javax.swing.JSpinner tankAmmoCount;
    private javax.swing.JSlider tankFuelCount;
    private javax.swing.JTextField tankMassage;
    private javax.swing.JButton tankMassageBtn;
    private javax.swing.JTextArea tankMsg;
    private javax.swing.JSpinner tankSoldierCount;
    // End of variables declaration//GEN-END:variables
}
